### PR TITLE
fixed style issues

### LINKED ISSUE #65: Responsive navbar collision between `About` and `Locale Switcher`
Need to avoid below collision
- responsive_navbar_collision

We should consider switching to hamburger design from this point (not ideal tho)
- navbar_should_become_hamburger_at_this_point

### PR DESCRIPTION
**Pull request by hiba-machfej**
This closes #65  #63. 
 

before 
Screen Shot 2021-07-29 at 2 08 15 PM

after 
Screen Shot 2021-07-29 at 2 10 32 PM

before 
Screen Shot 2021-07-12 at 11 22 53 AM

after 
Screen Shot 2021-07-29 at 3 38 49 PM

before 
responsive_navbar_collision

after at iPad size:
Screen Shot 2021-07-29 at 3 40 04 PM
Screen Shot 2021-07-29 at 3 40 09 PM

### CODE REVIEW

File: src/components/VideosList.vue [hunk 1]
```diff
@@ -11,7 +11,7 @@
                     <p class="text-sm font-medium text-near-green text-center">
                       {{ video.collection }}
                     </p>
-                    <p class="text-2xl font-semibold text-white">
+                    <p class="text-2xl font-semibold text-white w-64 text-center">
```
Comment (norrec99) [inline src/components/VideosList.vue:14]: If we use this style, we should be careful about very long video names because long video names will still overflow. 
eg. `near validators current near validators near validators current near validators`. You can try it on the dom.
However, I don't think there will be that long video names tho :D

**Review by norrec99 — APPROVED** [review]

File: src/components/VideosList.vue (hunk 1 above)
Comment (humanman) [reply src/components/VideosList.vue:14]: you can set font-size based on text length; just check the length, and make decisions on where those font-size breakpoints should be, e.g.` length > 50 ? font-size: 1.2rem : ...`

**Review by humanman — APPROVED** [review]
👍

**Review by BigDaddy-Zephyr — APPROVED** [review]

File: src/components/VideosList.vue (hunk 1 above)
Comment (hiba-machfej) [reply src/components/VideosList.vue:14]: yeah, also I think Airtable itself will limit the text length in the title.
